package forme;

import domen.KategorijaGosta;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Forma za prikaz detalja izabranog gosta i njegovih racuna.
 * Prikazuje osnovne podatke gosta, kategoriju, popust i agregirane
 * informacije o dugovanju, placenim i neplacenim racunima.
 *
 * @author Filip Oketic
 * @version 1.0
 */
public class DetaljiGostaForma extends javax.swing.JFrame {

    /**
     * Kreira formu i inicijalizuje Swing komponente.
     */
    public DetaljiGostaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacuni = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPlaceni = new javax.swing.JTextField();
        jTextFieldNeplacenih = new javax.swing.JTextField();
        jTextFieldDug = new javax.swing.JTextField();
        jTextFieldKategorija = new javax.swing.JTextField();
        jTextFieldUkupno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPopust = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRacuni);

        jLabel1.setText("Racuni");

        jLabel3.setText("id");

        jLabel4.setText("kategorija");

        jLabel2.setText("ime");

        jLabel5.setText("prezime");

        jLabel6.setText("broj neplacenih racuna");

        jLabel7.setText("broj placenih racuna");

        jLabel8.setText("ukupno racuna");

        jLabel9.setText("ukupan preostali dug");

        jLabel10.setText("popust");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldId)
                            .addComponent(jTextFieldKategorija)
                            .addComponent(jTextFieldPopust))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jTextFieldPlaceni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldUkupno)
                                        .addComponent(jTextFieldDug))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNeplacenih, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPlaceni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNeplacenih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldDug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vraca tabelu racuna.
     *
     * @return tabela racuna
     */
    public JTable getjTableRacuni() {
        return jTableRacuni;
    }

    /**
     * Postavlja tabelu racuna.
     *
     * @param jTableRacuni tabela racuna
     */
    public void setjTableRacuni(JTable jTableRacuni) {
        this.jTableRacuni = jTableRacuni;
    }

    /**
     * Vraca tekstualno polje za kategoriju.
     *
     * @return tekstualno polje za kategoriju
     */
    public JTextField getjTextFieldKategorija() {
        return jTextFieldKategorija;
    }

    /**
     * Postavlja tekstualno polje za kategoriju.
     *
     * @param jTextFieldKategorija tekstualno polje za kategoriju
     */
    public void setjTextFieldKategorija(JTextField jTextFieldKategorija) {
        this.jTextFieldKategorija = jTextFieldKategorija;
    }


    

    /**
     * Vraca tekstualno polje za dugovanje.
     *
     * @return tekstualno polje za dugovanje
     */
    public JTextField getjTextFieldDug() {
        return jTextFieldDug;
    }

    /**
     * Postavlja tekstualno polje za dugovanje.
     *
     * @param jTextFieldDug tekstualno polje za dugovanje
     */
    public void setjTextFieldDug(JTextField jTextFieldDug) {
        this.jTextFieldDug = jTextFieldDug;
    }

    /**
     * Vraca tekstualno polje za identifikator.
     *
     * @return tekstualno polje za identifikator
     */
    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    /**
     * Postavlja tekstualno polje za identifikator.
     *
     * @param jTextFieldId tekstualno polje za identifikator
     */
    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    /**
     * Vraca tekstualno polje za ime.
     *
     * @return tekstualno polje za ime
     */
    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    /**
     * Postavlja tekstualno polje za ime.
     *
     * @param jTextFieldIme tekstualno polje za ime
     */
    public void setjTextFieldIme(JTextField jTextFieldIme) {
        this.jTextFieldIme = jTextFieldIme;
    }

    /**
     * Vraca tekstualno polje za broj neplacenih racuna.
     *
     * @return tekstualno polje za broj neplacenih racuna
     */
    public JTextField getjTextFieldNeplacenih() {
        return jTextFieldNeplacenih;
    }

    /**
     * Postavlja tekstualno polje za broj neplacenih racuna.
     *
     * @param jTextFieldNeplacenih tekstualno polje za broj neplacenih racuna
     */
    public void setjTextFieldNeplacenih(JTextField jTextFieldNeplacenih) {
        this.jTextFieldNeplacenih = jTextFieldNeplacenih;
    }

    /**
     * Vraca tekstualno polje za broj placenih racuna.
     *
     * @return tekstualno polje za broj placenih racuna
     */
    public JTextField getjTextFieldPlaceni() {
        return jTextFieldPlaceni;
    }

    /**
     * Postavlja tekstualno polje za broj placenih racuna.
     *
     * @param jTextFieldPlaceni tekstualno polje za broj placenih racuna
     */
    public void setjTextFieldPlaceni(JTextField jTextFieldPlaceni) {
        this.jTextFieldPlaceni = jTextFieldPlaceni;
    }

    /**
     * Vraca tekstualno polje za prezime.
     *
     * @return tekstualno polje za prezime
     */
    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }

    /**
     * Postavlja tekstualno polje za prezime.
     *
     * @param jTextFieldPrezime tekstualno polje za prezime
     */
    public void setjTextFieldPrezime(JTextField jTextFieldPrezime) {
        this.jTextFieldPrezime = jTextFieldPrezime;
    }

    /**
     * Vraca tekstualno polje za ukupan broj racuna.
     *
     * @return tekstualno polje za ukupan broj racuna
     */
    public JTextField getjTextFieldUkupno() {
        return jTextFieldUkupno;
    }

    /**
     * Postavlja tekstualno polje za ukupan broj racuna.
     *
     * @param jTextFieldUkupno tekstualno polje za ukupan broj racuna
     */
    public void setjTextFieldUkupno(JTextField jTextFieldUkupno) {
        this.jTextFieldUkupno = jTextFieldUkupno;
    }

    /**
     * Vraca tekstualno polje za popust.
     *
     * @return tekstualno polje za popust
     */
    public JTextField getjTextFieldPopust() {
        return jTextFieldPopust;
    }

    /**
     * Postavlja tekstualno polje za popust.
     *
     * @param jTextFieldPopust tekstualno polje za popust
     */
    public void setjTextFieldPopust(JTextField jTextFieldPopust) {
        this.jTextFieldPopust = jTextFieldPopust;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel1;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel10;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel2;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel3;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel4;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel5;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel6;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel7;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel8;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel9;
    /** Swing komponenta. */
    private javax.swing.JScrollPane jScrollPane1;
    /** Swing komponenta. */
    private javax.swing.JTable jTableRacuni;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldDug;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldId;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldIme;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldKategorija;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldNeplacenih;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldPlaceni;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldPopust;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldPrezime;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldUkupno;
    // End of variables declaration//GEN-END:variables
}
