package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 * Forma za dodavanje novog ili izmenu postojeceg artikla.
 * Omogucava unos identifikatora, naziva, tipa i cene artikla.
 * Koristi se u dva moda koje kontroler postavlja pre prikaza.
 *
 * @author Filip Oketic
 * @version 1.0
 */
public class DodajArtikalForma extends javax.swing.JFrame {

    /**
     * Kreira formu i inicijalizuje Swing komponente.
     */
    public DodajArtikalForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCena = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldCena.setText("125");

        jButtonDodaj.setText("dodaj");

        jButtonIzmeni.setText("izmeni");

        jLabel3.setText("id");

        jLabel1.setText("naziv");

        jLabel2.setText("cena");

        jTextFieldNaziv.setText("Pepsi");

        jLabel4.setText("tip");

        jTextFieldTip.setText("Pice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNaziv)
                    .addComponent(jTextFieldCena)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTextFieldTip))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonIzmeni)
                .addGap(32, 32, 32)
                .addComponent(jButtonDodaj)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmeni)
                    .addComponent(jButtonDodaj))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vraca dugme za dodavanje.
     *
     * @return dugme za dodavanje
     */
    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    /**
     * Postavlja dugme za dodavanje.
     *
     * @param jButtonDodaj dugme za dodavanje
     */
    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    /**
     * Vraca dugme za izmenu.
     *
     * @return dugme za izmenu
     */
    public JButton getjButtonIzmeni() {
        return jButtonIzmeni;
    }

    /**
     * Postavlja dugme za izmenu.
     *
     * @param jButtonIzmeni dugme za izmenu
     */
    public void setjButtonIzmeni(JButton jButtonIzmeni) {
        this.jButtonIzmeni = jButtonIzmeni;
    }

    /**
     * Vraca tekstualno polje za cenu.
     *
     * @return tekstualno polje za cenu
     */
    public JTextField getjTextFieldCena() {
        return jTextFieldCena;
    }

    /**
     * Postavlja tekstualno polje za cenu.
     *
     * @param jTextFieldCena tekstualno polje za cenu
     */
    public void setjTextFieldCena(JTextField jTextFieldCena) {
        this.jTextFieldCena = jTextFieldCena;
    }

    /**
     * Vraca tekstualno polje za identifikator.
     *
     * @return tekstualno polje za identifikator
     */
    public JTextField getjTextFieldId() {
        return jTextFieldId;
    }

    /**
     * Postavlja tekstualno polje za identifikator.
     *
     * @param jTextFieldId tekstualno polje za identifikator
     */
    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    /**
     * Vraca tekstualno polje za naziv.
     *
     * @return tekstualno polje za naziv
     */
    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    /**
     * Postavlja tekstualno polje za naziv.
     *
     * @param jTextFieldNaziv tekstualno polje za naziv
     */
    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    /**
     * Vraca tekstualno polje za tip.
     *
     * @return tekstualno polje za tip
     */
    public JTextField getjTextFieldTip() {
        return jTextFieldTip;
    }

    /**
     * Postavlja tekstualno polje za tip.
     *
     * @param jTextFieldTip tekstualno polje za tip
     */
    public void setjTextFieldTip(JTextField jTextFieldTip) {
        this.jTextFieldTip = jTextFieldTip;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldTip;
    // End of variables declaration//GEN-END:variables

     /**
      * Dodaje ActionListener na dugme za dodavanje.
      *
      * @param actionListener osluskivac koji se poziva pri kliku na dugme za dodavanje
      */
     public void dodajAddActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }
    
    /**
     * Dodaje ActionListener na dugme za izmenu.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za izmenu
     */
    public void izmeniAddActionListener(ActionListener actionListener) {
        jButtonIzmeni.addActionListener(actionListener);
    }
}
