package forme;

import domen.Gost;
import domen.KategorijaGosta;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Forma za pregled, pretragu, izmenu i brisanje gostiju u klijentskoj aplikaciji.
 * Prikazuje tabelu gostiju i omogucava filtriranje po imenu, prezimenu i
 * kategoriji, kao i otvaranje detalja izabranog gosta.
 *
 * @author Filip Oketic
 * @version 1.0
 */
public class PrikazGostijuForma extends javax.swing.JFrame {

    /**
     * Kreira formu i inicijalizuje Swing komponente.
     */
    public PrikazGostijuForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGosti = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonResetuj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxKategorijaGosta = new javax.swing.JComboBox<>();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGosti);

        jButtonObrisi.setText("obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jLabel1.setText("ime");

        jLabel2.setText("prezime");

        jButtonPretrazi.setText("pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonResetuj.setText("restartuj pretragu");
        jButtonResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetujActionPerformed(evt);
            }
        });

        jLabel6.setText("kategorija gosta");

        jButtonDetalji.setText("detalji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110)
                        .addComponent(jComboBoxKategorijaGosta, 0, 165, Short.MAX_VALUE)
                        .addGap(172, 172, 172)
                        .addComponent(jButtonResetuj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPrezime))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jButtonPretrazi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jButtonIzmeni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jButtonDetalji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResetuj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxKategorijaGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jButtonObrisi)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIzmeni)
                        .addGap(82, 82, 82)
                        .addComponent(jButtonDetalji))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetujActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetujActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    /**
     * Vraca tabelu gostiju.
     *
     * @return tabela gostiju
     */
    public JTable getjTableGosti() {
        return jTableGosti;
    }

    /**
     * Vraca dugme za brisanje.
     *
     * @return dugme za brisanje
     */
    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    /**
     * Vraca dugme za pretragu.
     *
     * @return dugme za pretragu
     */
    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    /**
     * Postavlja dugme za pretragu.
     *
     * @param jButtonPretrazi dugme za pretragu
     */
    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    /**
     * Vraca tekstualno polje za ime.
     *
     * @return tekstualno polje za ime
     */
    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    /**
     * Postavlja tekstualno polje za ime.
     *
     * @param jTextFieldIme tekstualno polje za ime
     */
    public void setjTextFieldIme(JTextField jTextFieldIme) {
        this.jTextFieldIme = jTextFieldIme;
    }

    /**
     * Vraca tekstualno polje za prezime.
     *
     * @return tekstualno polje za prezime
     */
    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }

    /**
     * Postavlja tekstualno polje za prezime.
     *
     * @param jTextFieldPrezime tekstualno polje za prezime
     */
    public void setjTextFieldPrezime(JTextField jTextFieldPrezime) {
        this.jTextFieldPrezime = jTextFieldPrezime;
    }

    /**
     * Vraca dugme za izmenu.
     *
     * @return dugme za izmenu
     */
    public JButton getjButtonIzmeni() {
        return jButtonIzmeni;
    }

    /**
     * Postavlja dugme za izmenu.
     *
     * @param jButtonIzmeni dugme za izmenu
     */
    public void setjButtonIzmeni(JButton jButtonIzmeni) {
        this.jButtonIzmeni = jButtonIzmeni;
    }

    /**
     * Vraca dugme za resetovanje filtera.
     *
     * @return dugme za resetovanje filtera
     */
    public JButton getjButtonResetuj() {
        return jButtonResetuj;
    }

    /**
     * Postavlja dugme za resetovanje filtera.
     *
     * @param jButtonResetuj dugme za resetovanje filtera
     */
    public void setjButtonResetuj(JButton jButtonResetuj) {
        this.jButtonResetuj = jButtonResetuj;
    }

    /**
     * Vraca combo box za kategoriju gosta.
     *
     * @return combo box za kategoriju gosta
     */
    public JComboBox<KategorijaGosta> getjComboBoxKategorijaGosta() {
        return jComboBoxKategorijaGosta;
    }

    /**
     * Postavlja combo box za kategoriju gosta.
     *
     * @param jComboBoxKategorijaGosta combo box za kategoriju gosta
     */
    public void setjComboBoxKategorijaGosta(JComboBox<KategorijaGosta> jComboBoxKategorijaGosta) {
        this.jComboBoxKategorijaGosta = jComboBoxKategorijaGosta;
    }

    /**
     * Vraca dugme za prikaz detalja.
     *
     * @return dugme za prikaz detalja
     */
    public JButton getjButtonDetalji() {
        return jButtonDetalji;
    }

    /**
     * Postavlja dugme za prikaz detalja.
     *
     * @param jButtonDetalji dugme za prikaz detalja
     */
    public void setjButtonDetalji(JButton jButtonDetalji) {
        this.jButtonDetalji = jButtonDetalji;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Swing komponenta. */
    private javax.swing.JButton jButtonDetalji;
    /** Swing komponenta. */
    private javax.swing.JButton jButtonIzmeni;
    /** Swing komponenta. */
    private javax.swing.JButton jButtonObrisi;
    /** Swing komponenta. */
    private javax.swing.JButton jButtonPretrazi;
    /** Swing komponenta. */
    private javax.swing.JButton jButtonResetuj;
    /** Swing komponenta. */
    private javax.swing.JComboBox<KategorijaGosta> jComboBoxKategorijaGosta;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel1;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel2;
    /** Swing komponenta. */
    private javax.swing.JLabel jLabel6;
    /** Swing komponenta. */
    private javax.swing.JScrollPane jScrollPane1;
    /** Swing komponenta. */
    private javax.swing.JTable jTableGosti;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldIme;
    /** Swing komponenta. */
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    /**
     * Dodaje ActionListener na dugme za brisanje.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za brisanje
     */
    public void addBtnObrisiActionListener(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }
    
    /**
     * Dodaje ActionListener na dugme za izmenu.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za izmenu
     */
    public void addBtnIzmeniActionListener(ActionListener actionListener) {
        jButtonIzmeni.addActionListener(actionListener);
    }
    
    /**
     * Dodaje ActionListener na dugme za pretragu.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za pretragu
     */
    public void addBtnPretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    /**
     * Dodaje ActionListener na dugme za resetovanje filtera.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za resetovanje
     */
    public void addBtnResetujActionListener(ActionListener actionListener) {
        jButtonResetuj.addActionListener(actionListener);
    }
    
    /**
     * Dodaje ActionListener na dugme za prikaz detalja.
     *
     * @param actionListener osluskivac koji se poziva pri kliku na dugme za detalje
     */
    public void addBtnDetaljiActionListener(ActionListener actionListener) {
        jButtonDetalji.addActionListener(actionListener);
    }
}
